name: Staging Deploy to EC2
# stagingにpushされた時にjobを実行する
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: staging
        env:
          SECRET_KEY: ${{ secrets.STAGING_SECRET_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.STAGING_EC2_HOST }}
        run:  
          echo "$SECRET_KEY" > secret_key && chmod 600 secret_key        
          ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd /home/ec2-user/fon-hikari/ && git pull origin staging"
